### PR TITLE
Run the notebook locally

### LINKED ISSUE #4: Set LD_LIBRARY_PATH environment variable
To run the executable file on a local system, we need to append the following to `LD_LIBRARY_PATH` environment variable:

`/usr/local/MATLAB/MATLAB_Runtime/v910/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v910/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v910/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v910/extern/bin/glnxa64`

### LINKED ISSUE #6: libGL error: MESA-LOADER
On some linux systems, the notebook [notebooks/run_model_in_notebook.ipynb](https://github.com/EcoExtreML/processing/pull/5/files#diff-1751787c308b01a0e2f736c276a5c0797213e6f7e5f4c60a8733f1f03c2dcfdb) might result an error as:

```python
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

For more info, see this [message](https://github.com/EcoExtreML/processing/pull/5#issuecomment-1126174618). However, the notebook run can be successful.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
closes #4  
closes #6

### CODE REVIEW

**Comment by SarahAlidoost** [comment]
@geek-yang After setting the environment variable, the notebook run was successful. However, as can be seen in the notebook, there are some errors related to `libGL` as:

```python
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

I am wondering if you get the same error. I am exploring it :)

**Comment by geek-yang** [comment]
> @geek-yang After setting the environment variable, the notebook run was successful. However, as can be seen in the notebook, there are some errors related to `libGL` as:
> 
> ```python
> libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: iris
> libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: iris
> libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: swrast
> ```
> 
> I am wondering if you get the same error. I am exploring it :)

Hi @SarahAlidoost , this looks really weird... I haven't encountered something like these. Not sure what's going wrong. But this seems to be a notorious issue if you google it. There is one [post](https://www.mathworks.com/matlabcentral/answers/534438-libgl-error-in-linux) from matlab forum might help. It seems these errors are related to linux os updates.

**Comment by SarahAlidoost** [comment]
> > @geek-yang After setting the environment variable, the notebook run was successful. However, as can be seen in the notebook, there are some errors related to `libGL` as:
> > ```python
> > libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> > libGL error: failed to load driver: iris
> > libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> > libGL error: failed to load driver: iris
> > libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> > libGL error: failed to load driver: swrast
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am wondering if you get the same error. I am exploring it :)
> 
> Hi @SarahAlidoost , this looks really weird... I haven't encountered something like these. Not sure what's going wrong. But this seems to be a notorious issue if you google it. There is one [post](https://www.mathworks.com/matlabcentral/answers/534438-libgl-error-in-linux) from matlab forum might help. It seems these errors are related to linux os updates.

Thanks for looking into this. I will submit an issue to be fixed in the future and make this PR ready for a review.

**Review by geek-yang — APPROVED** [review]
Sounds good. Thanks for creating an issue for it. Let's merge this branch now and address the issue in another PR.

**Comment by geek-yang** [comment]
I am somehow blocked by the error even after configuring the `LD_LIBRARY_PATH` manually
```sh
exe/STEMMUS_SCOPE: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory
```

I did some googling but most of the answers just pointed me to the `LD_LIBRARY_PATH` variable, which didn't work in my case. I will try to do more searching and keep you posted if something works for me.

**Comment by SarahAlidoost** [comment]
> I am somehow blocked by the error even after configuring the `LD_LIBRARY_PATH` manually
> 
> ```shell
> exe/STEMMUS_SCOPE: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory
> ```
> 
> I did some googling but most of the answers just pointed me to the `LD_LIBRARY_PATH` variable, which didn't work in my case. I will try to do more searching and keep you posted if something works for me.

Hi Yang, there is a cell inside the notebook on how to set the environment variable. You need to uncomment and run it. Also, this PR fixed this issue #4. Did you run that cell?

**Comment by SarahAlidoost** [comment]
@geek-yang thanks for reviewing and addressing the bugs. Please have a look at my last two commits.

**Comment by geek-yang** [comment]
> @geek-yang thanks for reviewing and addressing the bugs. Please have a look at my last two commits.

They look good to me. And it works on my machine. Let's merge this PR. Thanks @SarahAlidoost !

**Pull request merged**
